### ISSUE TITLE
Upgraded to ^5.1 and getting nasty error.

### ISSUE THREAD

**Issue by mryarbles** [angular-redux/ng2-redux#307] opened 2017-01-09 06:58 UTC
Error: Can't resolve all parameters for NgRedux: (?). at SyntaxError.BaseError [as constructor] (http://localhost:1337/js/vendor.bundle.js:106561:27) 

My store set up looks like this:

`export class StoreModule {
	constructor(
			private _redux: NgRedux<IAppState>
	) {

		console.log("StoreModule");
		// configure redux
		_redux.configureStore(
				appReducer,
				{},
				[ reduxLogger() ]
		);

	}
}`

**Comment by Renader** [comment] 2017-01-09 10:49
Same for me.. with angular cli beta.24 after updating ng2-redux to latest version

**Comment by sangress** [comment] 2017-01-09 15:23
same here. 
Angular@2.4.2
angular/router@3.4.2
zone.js@0.7.4
typescript@2.1.4

**Comment by SethDavenport** [comment] 2017-01-10 02:49
Looking into it. Although @sangress I can tell you right away that Typescript 2.1.4 won't work: Angular itself isn't compatible with it.

You'll have to pin that dependency to 2.0.10.

**Comment by SethDavenport** [comment] 2017-01-10 03:14
@mryarbles I can't reproduce the issue. However I notice that you're not specifying a generic argument for NgRedux in your constructor. Can you try again with this:

```typescript
export class StoreModule {
  constructor(
    private _redux: NgRedux<any> // <--- the <any> is new.
  ) {
	console.log("StoreModule");
	// configure redux
	_redux.configureStore(
          appReducer,
	  {},
	  [ reduxLogger() ]
	);
  }
}
```

**Comment by mryarbles** [comment] 2017-01-10 07:16
**I updated configureStore block to**:
`export class StoreModule {
  constructor(
    redux: NgRedux<any> // <--- the <any> is needed.
  ) {
	console.log("StoreModule");
	// configure redux
	redux.configureStore(
          appReducer,
	  {},
	  [  ]
	);
  }
}`

Had no effect.  

**Downgraded type script to 2.0.10**

Had no effect

This is the full stack trace:

"Error: Can't resolve all parameters for NgRedux: (?).
    at SyntaxError.BaseError [as constructor] (http://localhost:1337/js/vendor.bundle.js:106561:27) [<root>]
    at new SyntaxError (http://localhost:1337/js/vendor.bundle.js:6639:16) [<root>]
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:1337/js/vendor.bundle.js:19373:31) [<root>]
    at CompileMetadataResolver._getTypeMetadata (http://localhost:1337/js/vendor.bundle.js:19248:26) [<root>]
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:1337/js/vendor.bundle.js:19236:21) [<root>]
    at CompileMetadataResolver.getProviderMetadata (http://localhost:1337/js/vendor.bundle.js:19478:40) [<root>]
    at http://localhost:1337/js/vendor.bundle.js:19436:49 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:1337/js/vendor.bundle.js:19403:19) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:1337/js/vendor.bundle.js:19087:50) [<root>]
    at CompileMetadataResolver.getNgModuleSummary (http://localhost:1337/js/vendor.bundle.js:18943:52) [<root>]
    at http://localhost:1337/js/vendor.bundle.js:19014:72 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:1337/js/vendor.bundle.js:19001:49) [<root>]"

**Comment by SethDavenport** [comment] 2017-01-10 13:53
Hmm. I personally have never seen that specific error. However it suggests that something weird is going on with the timing of bootstrap and dependency injection.  One change that happened in 5.1 is that NgRedux itself now has a dependency on NgZone. Angular's DI appears to not be finding that when your StoreModule is getting created.

Can you give me more insight as to the structure of your app from an NgModule point of view?

I'm assuming `StoreModule` is a sub-module of your app's app module, right? Can you post the `@NgModule` decorator invocation for `StoreModule` and for your app's `AppModule`?

**Comment by SethDavenport** [comment] 2017-01-10 13:58
Also your getting this error at the command line or in the browser console? What command are you using? I'm guessing 'ng serve --aot'?

**Comment by CanKattwinkel** [comment] 2017-01-10 15:08
I'm experiencing the same issue with ng2 redux `v4.0.0-beta.3` or `v5.1.0.`

Both work **with --aot** flag.

 Without ->  `Uncaught Error: Can't resolve all parameters for NgRedux: (?).` 

TS: `"typescript": "~2.0.10"`

**Comment by SethDavenport** [comment] 2017-01-10 15:32
Can you post what's in your @NgModule decorators? Both for your AppModule and your StoreModule?

**Comment by SethDavenport** [comment] 2017-01-10 20:52
As an aside - it doesn't make a lot of sense to put NgRedux's store in a submodule.  Submodules are there to enable lazy loading; however the redux store cannot reasonably be lazy loaded since it's a global store.

So it might as well live in your appModule.

**Comment by SethDavenport** [comment] 2017-01-10 20:53
Is your storeModule `import` ing `NgReduxModule`?

**Comment by e-schultz** [comment] 2017-01-10 20:58
If we could get a repo reproducing the issue it'd be greatly appreciated.

I haven't done store configuration in a submodule before, but just tried it out with 5.1 and the most recent CLI beta, and have a setup like:

```js


@NgModule({
  
})
export class StoreModule {
  constructor(ngRedux: NgRedux<AppState>) {
    const rootReducer = combineReducers<AppState>({ projects, users });
    const logger = createLogger();

    ngRedux.configureStore(rootReducer,
      {},
      [logger]);
    
    ngRedux.dispatch({ type: 'hiii' });

  }
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    NgReduxModule,
    BrowserModule,
    HttpModule,
    CoreModule,
    SharedModule,
    StoreModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule {

}
```

and things were working - only time I can get any errors relating to not being able to resolve dependencies, is if I don't include `BrowserModule` so that NGZone isn't available.

**Comment by SethDavenport** [comment] 2017-01-11 03:54
OK... thanks to @CanKattwinkel kindly sharing a bit more info with me offline I'm able to reproduce the issue.

**Comment by SethDavenport** [comment] 2017-01-11 03:56
In @CanKattwinkel's case, the error appears to be triggered by this:

```typescript
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {NgRedux, NgReduxModule} from "ng2-redux";

@NgModule({
  imports: [
    CommonModule,
    NgReduxModule
  ],
  declarations: [],
  providers: [
    NgRedux, // <--- The trigger
    // ... other internal modules, omitted for brevity
  ]
})
export class ReduxModule {
}
```

**Comment by SethDavenport** [comment] 2017-01-11 03:57
Releases 4 and 5 fixed a few issues in the way we were setting up our `NgReduxModule` internally; it now exports the appropriate providers so you don't need to add them to your module's `providers` any more.

In fact it appears to be detrimental to do so at least in this case, since it's the cause of the error you've reported.

**Comment by SethDavenport** [comment] 2017-01-11 04:01
@mryarbles, @sangress, @Renader can you check whether you're adding `NgRedux` to your module's providers? You no longer need to - try doing it with just an import of `NgReduxModule` instead.

**Comment by SethDavenport** [comment] 2017-01-11 04:01
@e-schultz FYI

**Comment by sangress** [comment] 2017-01-11 11:56
@SethDavenport I removed NgRedux from the providers, now it works well. 10X!
BTW: I use typescript 2.1.4 with ng2 and have no issues with that.

**Comment by SethDavenport** [comment] 2017-01-11 19:33
Seems that this is the solution then. Closing.

**Closed by SethDavenport** 2017-01-11 19:33 UTC

**Comment by mryarbles** [comment] 2017-01-12 18:21
Sorry, this is just a side project so I was out of pocket for a few days.  Removing instance of 

providers:[NgRedux]

fixed error. Thanks.

This experience is making me reconsider using Angular.

**Comment by crowmagnumb** [comment] 2017-01-25 19:27
Thank you! The provider change fixed it for me too!
