### ISSUE TITLE
Build with ngc 2.3.x fails (again) 

### ISSUE THREAD

**Issue by DcsMarcRemolt** [angular-redux/ng2-redux#282] opened 2016-12-15 09:29 UTC
When upgrading a project to angular 2.3.1 the AOT compiler fails on the line where I import NgReduxModule: 

```typescript
@NgModule({
  imports: [
    ...
    NgReduxModule.forRoot()
})
export class MainModule {  }
```

Commenting out the line ngc runs through, but the whole build fails later of course,

The error is again the not very helpful and generic

Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol MainModule in .../src/main.module.ts, resolving symbol MainModule in .../src/main.module.ts

**Comment by aitboudad** [comment] 2016-12-16 21:43
I would prefer to report this issue on angular

**Comment by JCThomas4214** [comment] 2016-12-17 04:53
I have this exact problem. While trying to figure out why ngc was not working with TS2.1 [here](https://github.com/angular/angular/issues/13204), I came across this when compiling with angular 2.3.0. I mentioned it on that angular issue and actra-gschuster told me the following...

> That's not an issue with NG or TSC, it's just because you're not exporting the lambda function and thus NG is unable to resolve it statically.
> E.g. instead of writing:
> `let x: any = { abc: (foo: any) => foo.bar };`
> just write it as:
> `export const callback = (foo: any) => foo.bar; let x: any = { abc: callback };`

**Comment by NeoLSN** [comment] 2016-12-19 06:47
Same issue here.
When I upgrade angular@2.2.1 then the library doesn't work.

**Comment by duydao** [comment] 2016-12-19 21:04
@NeoLSN I'm assuming that you're using ionic RC.4.

The problem is the same, ionic will remove any decorators in an AOT build. This seems to be a thing now...

https://github.com/driftyco/ionic-app-scripts/blob/master/src/util/typescript-utils.ts#L22-L31

As a workaround, I've modify the file in my node_modules folder and return the source without modification. Good luck!

**Comment by e-schultz** [comment] 2016-12-21 17:57
The new beta of the angular-cli isn't stripping out all decorators anymore (yay) - hopefully Ionic fixes this also.

**Comment by SethDavenport** [comment] 2016-12-27 02:35
This will need to be fixed in v5 since it's a breaking change to the API.

**Comment by SethDavenport** [comment] 2016-12-27 03:17
`forRoot` has been removed in our v5.x branch. Give 5.0.0-beta.0 a try and let me know. We've updated the Angular peer dependency to 2.4.1 as well.

**Closed by SethDavenport** 2016-12-27 03:17 UTC
